# Site settings
title: Page de Colas Bardavid
author: Colas Bardavid

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote-theme: mmistakes/minimal-mistakes
#theme: minimal-mistakes-jekyll
