# Site settings
title: Page de Colas Bardavid
author: Colas Bardavid

# Build settings
plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.19.3"
#theme: minimal-mistakes-jekyll
