# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "fr-FR"
url: "https://colasbd.github.io"

title: Site de Colas Bardavid, professeur de mathématiques en CPGE
masthead_title: " "
email:
description: >- # this means to ignore newlines until "baseurl:"
  Page de Colas Bardavid. Documents mathématiques pour étudiants en classes préparatoires MPSI, MP2I,
  PCSI, PTSI, CAPES, agrégation, etc.
#twitter_username: __colas
github_username: colasbd
minimal_mistakes_skin: air #neon #mint #contrast #default
search: false #true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Paris" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name      : "Colas Bardavid"
  avatar    : "/assets/images/photoColas.jpg"
  bio       : "Professeur de mathématiques et d'informatique en classes préparatoires"
  biobis    : "[Lycée Sainte-Geneviève](https://www.bginette.com)"

  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/colasbd"
    - label: "Improov Maths"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Improov_Maths"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/__colas"
    #- label: "Improov"
    #  icon: "fas fa-fw fa-link"
    #  url: "http://www.improov.fr"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/colasbd"
    - label: "Improov Maths"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Improov_Maths"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/__colas"
    #- label: "Improov"
    #  icon: "fas fa-fw fa-link"
    #  url: "http://www.improov.fr"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
